// <auto-generated />
namespace EducationalProject.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class EmailLikeLogin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EmailLikeLogin));
        
        string IMigrationMetadata.Id
        {
            get { return "201411092327534_EmailLikeLogin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
