// <auto-generated />
namespace EduTesting.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class UserAnswer_QuestionId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserAnswer_QuestionId));
        
        string IMigrationMetadata.Id
        {
            get { return "201501201119498_UserAnswer_QuestionId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
